services:
  postgres-master:
    image: postgres:17-alpine
    container_name: postgres-master
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 5s
      retries: 5

  be-queries:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1235:8080
    environment:
        ASPNETCORE_ENVIRONMENT: "Development"
    links:
      - postgres-master
    depends_on:
      postgres-master:
        condition: service_healthy