services:

  postgres-master:
    image: postgres:17-alpine
    container_name: postgres-master
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  be-base:
    build:
      context: .
      dockerfile: Dockerfile-Base
    image: be-base-image:latest
    command: ["true"]

  be-queries:
    build:
      context: .
      dockerfile: ./src/Wage/Queries/Dockerfile
    ports:
      - 1234:8080
    environment:
      Database:Wage: "User ID=${DOCKER_DB_USERNAME};Password=${DOCKER_DB_PASSWORD};Host=postgres-master;Port=5432;Database=${DOCKER_DB_DATABASE};Include Error Detail=true;"
      ASPNETCORE_ENVIRONMENT: "Development"
    links:
      - postgres-master
    depends_on:
      postgres-master:
        condition: service_healthy
      be-base:
        condition: service_completed_successfully

  be-commands:
    build:
      context: .
      dockerfile: ./src/Wage/Commands/Dockerfile
    ports:
      - 1235:8080
    environment:
      Database:Wage: "User ID=${DOCKER_DB_USERNAME};Password=${DOCKER_DB_PASSWORD};Host=postgres-master;Port=5432;Database=${DOCKER_DB_DATABASE};Include Error Detail=true;"
      ASPNETCORE_ENVIRONMENT: "Development"
    links:
      - postgres-master
    depends_on:
      postgres-master:
        condition: service_healthy
      be-base:
        condition: service_completed_successfully
