# Use the official .NET SDK image for building
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /app

# Copy only the csproj files first and restore (cacheable step)
COPY *.sln .
COPY ./src/Wage/Commands/*/*.csproj .
RUN for file in $(ls *.csproj); do mkdir -p src/Wage/Commands/${file%.*}/ && mv $file src/Wage/Commands/${file%.*}/; done
COPY ./src/Shared/Commands/*/*.csproj .
RUN for file in $(ls *.csproj); do mkdir -p src/Shared/Commands/${file%.*}/ && mv $file src/Shared/Commands/${file%.*}/; done
COPY ./src/Wage/Commands/*/*.csproj .
RUN for file in $(ls *.csproj); do mkdir -p src/Wage/Commands/${file%.*}/ && mv $file src/Wage/Commands/${file%.*}/; done
COPY ./src/Shared/*/*.csproj .
RUN for file in $(ls *.csproj); do mkdir -p src/Shared/${file%.*}/ && mv $file src/Shared/${file%.*}/; done
COPY ./src/Wage/Queries/*/*.csproj .
RUN for file in $(ls *.csproj); do mkdir -p src/Wage/Queries/${file%.*}/ && mv $file src/Wage/Queries/${file%.*}/; done
COPY ./src/Shared/Queries/*/*.csproj .
RUN for file in $(ls *.csproj); do mkdir -p src/Shared/Queries/${file%.*}/ && mv $file src/Shared/Queries/${file%.*}/; done
COPY ./src/Wage/Queries/*/*.csproj .
RUN for file in $(ls *.csproj); do mkdir -p src/Wage/Queries/${file%.*}/ && mv $file src/Wage/Queries/${file%.*}/; done

# Automatic hashing to check if any files changed
RUN dotnet restore

# Now copy the rest of the source
COPY . .

# Build and publish
# Using --no-restore because if something hasn't been restored
# (e.g, due to wrong paths), it will throw an error here
RUN dotnet publish -c Release -o ./app --no-restore

# Runtime image
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/app ./
EXPOSE 8080
ENTRYPOINT ["dotnet", "FinancePlanner.Wage.Commands.API.dll"]
