FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /App

COPY ./*.sln .
# Copy and move packages to their directories
COPY ./src/Commands/*/*.csproj .
RUN for file in $(ls *.csproj); do mkdir -p src/Shared/${file%.*}/ && mv $file src/Shared/${file%.*}/; done
COPY ./src/Queries/*/*.csproj .
RUN for file in $(ls *.csproj); do mkdir -p src/Commands/${file%.*}/ && mv $file src/Commands/${file%.*}/; done
COPY ./src/Shared/*/*.csproj .
RUN for file in $(ls *.csproj); do mkdir -p src/Queries/${file%.*}/ && mv $file src/Queries/${file%.*}/; done
# Restore as distinct layers
RUN dotnet restore 
# Copy everything else
COPY . .
# Build and publish a release
RUN dotnet publish -c Release -o out --no-restore
