services:
  postgres-master:
    image: postgres:17-alpine
    container_name: postgres-master
    ports:
      - ${DOCKER_DB_OUTBOUND_PORT}:5432
    environment:
      - POSTGRES_DB=${DOCKER_DB_DATABASE}
      - POSTGRES_USER=${DOCKER_DB_USERNAME}
      - POSTGRES_PASSWORD=${DOCKER_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DOCKER_DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - master-database:/var/lib/postgresql/data

  be-queries:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1235:8080
    environment:
    links:
      - postgres-master
    depends_on:
      postgres-master:
        condition: service_healthy